# https://taskfile.dev

version: "3"

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  build:
    desc: build
    cmds:
      - docker compose build

  start:
    desc: start
    cmds:
      - docker compose up

  init:
    desc: init a new project
    cmds:
      - ng new web-ingegno

  cli:
    desc: build
    cmds:
      - docker compose run --rm web sh

  compile:
    desc: compile for production
    cmds:
      - sudo rm -fR ./web-ingegno/www
      - docker run --rm -v ./web-ingegno/src:/app/src -v ./web-ingegno/www:/app/www ingegno/dev/web ./build.sh