repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
      stages: [pre-commit]
    - id: end-of-file-fixer
      stages: [pre-commit]
    - id: trailing-whitespace
      stages: [pre-commit]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
    - id: prettier
    stages: [pre-commit]