# Prettier intentionally doesn’t support any kind of global configuration. 

# The only options that can be changed in the configuration file are:
# for more explanations and examples refer to: https://prettier.io/docs/en/options.html

printWidth: 80 # int - Specify the line length that the printer will wrap on
tabWidth: 2 # int - Specify the number of spaces per indentation-level
useTabs: false # bool - Indent lines with tabs instead of spaces
semi: true # bool - Print semicolons at the ends of statements
singleQuote: false # bool - Use single quotes instead of double quotes
quoteProps: "as-needed" # as-needed | consistent | preserve - Change when properties in objects are quoted
jsxSingleQuote: false # bool - Use single quotes instead of double quotes in JSX
trailingComma: "all" # all | es5 | none - Print trailing commas wherever possible in multi-line comma-separated syntactic structures.
bracketSpacing: true # bool - Print spaces between brackets in object literals
bracketSameLine: false # bool - Put the > of a multi-line HTML (HTML, JSX, Vue, Angular) element at the end of the last line instead of being alone on the next line (does not apply to self closing elements).
arrowParens: "always" # always | avoid - Include parentheses around a sole arrow function parameter
rangeStart: 0 # int - Format only a segment of a file
rangeEnd: Infinity # int - Format only a segment of a file
parser: None # string - Specify which parser to use
filepath: None # string - Specify the file name to use to infer which parser to use
requirePragma: false # bool - Prettier can restrict itself to only format files that contain a special comment, called a pragma, at the top of the file
insertPragma: false # bool - Prettier can insert a special @format marker at the top of files specifying that the file has been formatted with Prettier
proseWrap: "preserve" # always | never | preserve - By default, Prettier will not change wrapping in markdown text since some services use a linebreak-sensitive renderer, e.g. GitHub comments and BitBucket
htmlWhitespaceSensitivity: "css" # css | strict | ignore - Specify the global whitespace sensitivity for HTML, Vue, Angular, and Handlebars
vueIndentScriptAndStyle: false # bool - Whether or not to indent the code inside <script> and <style> tags in Vue files
endOfLine: "lf" # lf | crlf | cr | auto - When people collaborate on a project from different operating systems, it becomes easy to end up with mixed line endings in a shared git repository
embeddedLanguageFormatting: "auto" # off auto - Control whether Prettier formats quoted code embedded in the file.
singleAttributePerLine: false # bool - Enforce single attribute per line in HTML, Vue and JSX



# Configuration Overrides for specific formats:
semi: false
overrides:
  - files: "*.test.js" #files is required for each override (string or array of strings)
    options:
      semi: true
  - files:
      - "*.html"
      - "legacy/**/*.js"
    options:
      tabWidth: 4
  - excludeFiles: "" #optional


# You can also add a parser to format files prettier does not recognize:
# Note: NEVER put the parser option at the top level of your configuration, ONLY use it inside overrides

overrides:
    - files: ".prettierrc"
      options:
        parser: "json"
