# https://taskfile.dev

version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  build:
    desc: build 
    cmds:
      - docker compose build 

  start:
    desc: start
    cmds:
      - docker compose up

  venv:
    desc: virtualenv
    cmds: 
      - |
        python -m venv .venv
        source .venv/bin/activate
        # pip install 